### ISSUE TITLE
What is the best way to start testing the trigger?

### ISSUE THREAD

**Issue by giorgosn** [Joffcom/n8n-nodes-rss-feed-trigger#2]
Hey! Great job!
I have downloaded the desktop app but I can not find any documentation.  
Should I install it manually?

**Comment by Joffcom** [comment]
Hey @giorgosn,

The current version of the desktop app doesn't easily support using custom nodes yet, npm may be the easier way to get started or I would say manually implementing the polling logic could be a good solution until custom nodes are available in desktop.
